version: 1.0.{build}
image: Visual Studio 2019
before_build:
  - nuget restore
build:
configuration:
  - Release
  project: SeManageVolumeAbuse.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: x64\*\*.exe
only_commits:
  files:
    - SeManageVolumeAbuse/
